# Generated by Django 6.0.5 on 2026-06-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=128)),
                ('business_account_id', models.CharField(blank=True, max_length=128)),
                ('access_token', models.TextField()),
                ('verify_token', models.CharField(max_length=255)),
                ('numero_whatsapp', models.CharField(blank=True, max_length=32)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_whatsapp', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'configuración WhatsApp',
                'verbose_name_plural': 'configuraciones WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='ErrorWebhookWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_webhook_whatsapp', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'error de webhook WhatsApp',
                'verbose_name_plural': 'errores de webhook WhatsApp',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inicio', 'Inicio'), ('menu_principal', 'Menú principal'), ('esperando_servicio', 'Esperando servicio'), ('esperando_fecha', 'Esperando fecha'), ('esperando_hora', 'Esperando hora'), ('esperando_confirmacion_turno', 'Esperando confirmación de turno'), ('esperando_reagendar_fecha', 'Esperando reagendar fecha'), ('esperando_reagendar_hora', 'Esperando reagendar hora'), ('esperando_cancelacion', 'Esperando cancelación'), ('esperando_confirmacion_cancelacion', 'Esperando confirmación de cancelación'), ('esperando_humano', 'Esperando humano'), ('finalizado', 'Finalizado')], default='inicio', max_length=48)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_whatsapp', to='agenda.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_whatsapp', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'conversación WhatsApp',
                'verbose_name_plural': 'conversaciones WhatsApp',
                'ordering': ['-actualizado'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'cliente'), name='conversacion_unica_por_negocio_cliente')],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=16)),
                ('telefono', models.CharField(max_length=32)),
                ('mensaje', models.TextField(blank=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=128)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='agenda.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_whatsapp', to='negocios.negocio')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='agenda.turno')),
            ],
            options={
                'verbose_name': 'mensaje WhatsApp',
                'verbose_name_plural': 'mensajes WhatsApp',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['negocio', 'telefono'], name='whatsapp_ap_negocio_0a5f93_idx'), models.Index(fields=['whatsapp_message_id'], name='whatsapp_ap_whatsap_ce357f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación'), ('24h', '24 horas'), ('2h', '2 horas'), ('post_cita', 'Post cita'), ('no_asistio', 'No asistió'), ('reactivacion', 'Reactivación')], max_length=24)),
                ('mensaje', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_whatsapp', to='agenda.turno')),
            ],
            options={
                'verbose_name': 'recordatorio WhatsApp',
                'verbose_name_plural': 'recordatorios WhatsApp',
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['enviado', 'fecha_programada'], name='whatsapp_ap_enviado_ce4a78_idx')],
                'constraints': [models.UniqueConstraint(fields=('turno', 'tipo'), name='recordatorio_unico_por_turno_tipo')],
            },
        ),
    ]
