# Generated by Django 6.0.5 on 2026-06-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('menu_principal', 'Menú principal'), ('esperando_servicio', 'Esperando servicio'), ('esperando_fecha', 'Esperando fecha'), ('esperando_hora', 'Esperando hora'), ('esperando_confirmacion_turno', 'Esperando confirmación de turno'), ('esperando_producto', 'Esperando producto'), ('esperando_cantidad_producto', 'Esperando cantidad de producto'), ('esperando_confirmacion_pedido', 'Esperando confirmación de pedido'), ('esperando_reagendar_fecha', 'Esperando reagendar fecha'), ('esperando_reagendar_hora', 'Esperando reagendar hora'), ('esperando_cancelacion', 'Esperando cancelación'), ('esperando_confirmacion_cancelacion', 'Esperando confirmación de cancelación'), ('esperando_humano', 'Esperando humano'), ('finalizado', 'Finalizado')], default='inicio', max_length=48),
        ),
    ]
