# Generated by Django 6.0.5 on 2026-06-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0002_alter_conversacionwhatsapp_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='app_secret',
            field=models.CharField(blank=True, help_text='App Secret de la app de Meta. Si se define, se valida la firma X-Hub-Signature-256 del webhook.', max_length=255),
        ),
    ]
