# Generated by Django 6.0.5 on 2026-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0004_alter_recordatoriowhatsapp_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatoriowhatsapp',
            name='tipo',
            field=models.CharField(choices=[('confirmacion', 'Confirmación'), ('24h', '24 horas'), ('2h', '1 hora'), ('post_cita', 'Post cita'), ('no_asistio', 'No asistió'), ('reactivacion', 'Reactivación'), ('control', 'Control / seguimiento')], max_length=24),
        ),
    ]
