# Generated by Django 6.0.5 on 2026-06-03 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('telefono_principal', models.CharField(max_length=32)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=32)),
                ('direccion', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios/logos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocioBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_bienvenida', models.TextField(default='Hola, soy el asistente virtual de {negocio}. ¿Qué deseas hacer?')),
                ('mensaje_fuera_horario', models.TextField(default='En este momento estamos fuera de horario. Puedes dejar tu solicitud y te responderemos pronto.')),
                ('permite_agendar_automatico', models.BooleanField(default=True)),
                ('requiere_confirmacion_manual', models.BooleanField(default=False)),
                ('envia_recordatorio_24h', models.BooleanField(default=True)),
                ('envia_recordatorio_2h', models.BooleanField(default=True)),
                ('notificar_dueno_whatsapp', models.BooleanField(default=True)),
                ('telefono_notificacion_dueno', models.CharField(blank=True, max_length=32)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_bot', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'configuración del bot del negocio',
                'verbose_name_plural': 'configuraciones del bot del negocio',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='negocios.negocio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='negocios.sucursal')),
            ],
            options={
                'verbose_name': 'horario de atención',
                'verbose_name_plural': 'horarios de atención',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
