# Generated by Django 6.0.5 on 2026-06-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnegociobot',
            name='mensaje_bienvenida',
            field=models.TextField(default='Hola, soy la recepción virtual de {negocio}. Puedo ayudarte a agendar, consultar precios, ver productos, promociones o hablar con una persona.'),
        ),
    ]
