# Generated by Django 6.0.5 on 2026-06-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('telefono', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('especialidad', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='negocios.negocio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='negocios.sucursal')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_horario', to='negocios.negocio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_horario', to='negocios.sucursal')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_horario', to='agenda.profesional')),
            ],
            options={
                'verbose_name': 'bloqueo de horario',
                'verbose_name_plural': 'bloqueos de horario',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deseada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('tomado', 'Tomado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=24)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='agenda.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='negocios.negocio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='agenda.servicio')),
            ],
            options={
                'verbose_name': 'lista de espera',
                'verbose_name_plural': 'listas de espera',
                'ordering': ['fecha_deseada', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('reagendado', 'Reagendado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('no_asistio', 'No asistió')], default='pendiente', max_length=24)),
                ('origen', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('panel', 'Panel'), ('manual', 'Manual')], default='whatsapp', max_length=24)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='negocios.negocio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='agenda.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='agenda.servicio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='negocios.sucursal')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('negocio', 'telefono'), name='cliente_unico_por_negocio_telefono'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['negocio', 'activo', 'fecha_hora_inicio'], name='agenda_bloq_negocio_194a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['negocio', 'fecha_hora_inicio'], name='agenda_turn_negocio_e4da82_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['cliente', 'estado'], name='agenda_turn_cliente_e29148_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['profesional', 'fecha_hora_inicio'], name='agenda_turn_profesi_f8edd3_idx'),
        ),
    ]
