# Generated by Django 6.0.5 on 2026-06-11 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_preguntafrecuente_producto_pedidowhatsapp'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_whatsapp', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'promoción WhatsApp',
                'verbose_name_plural': 'promociones WhatsApp',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
