# Generated by Django 6.0.5 on 2026-07-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_cliente_fecha_nacimiento'),
        ('negocios', '0002_alter_configuracionnegociobot_mensaje_bienvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_cumple_saludado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(help_text='Qué se hizo en la visita: tratamiento, procedimiento, observaciones.')),
                ('producto_libre', models.CharField(blank=True, help_text='Producto/crema que no está en el catálogo.', max_length=160)),
                ('producto_accion', models.CharField(choices=[('ninguno', 'Sin producto'), ('aplicado', 'Aplicado'), ('vendido', 'Vendido'), ('recomendado', 'Recomendado')], default='ninguno', max_length=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='agenda.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='negocios.negocio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='agenda.producto')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='agenda.profesional')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='agenda.servicio')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='agenda.turno')),
            ],
            options={
                'verbose_name': 'registro de atención',
                'verbose_name_plural': 'registros de atención',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='agenda_regi_cliente_e855e7_idx')],
            },
        ),
    ]
