# Generated by Django 6.0.5 on 2026-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cliente_ultimo_cumple_saludado_registroatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatencion',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='atenciones/'),
        ),
        migrations.AddField(
            model_name='registroatencion',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='atenciones/'),
        ),
        migrations.AddField(
            model_name='registroatencion',
            name='proximo_control',
            field=models.DateField(blank=True, help_text='Cuándo debería volver para seguimiento.', null=True),
        ),
    ]
