# Generated by Django 6.0.5 on 2026-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_registroatencion_foto_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatencion',
            name='producto_cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registroatencion',
            name='producto_precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta en esta visita (si se vendió).', max_digits=10),
        ),
    ]
